apiVersion: v1
kind: Service
metadata:
  name: lnd-pod
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: peer
    port: 9735
    targetPort: 9735
  selector:
    name: lnd-pod
  type: LoadBalancer
